import { Paciente, Prontuario, Agendamento, Profissional } from './types';

export const mockProfissional: Profissional = {
  nome: 'Dr. Jeferson Brandão',
  cro: 'CRO-SP 12345',
  email: 'jeferson@optoflow.com.br',
  telefone: '(11) 99999-0000',
  endereco: 'Av. Paulista, 1000 - Sala 302',
  cidade: 'São Paulo',
  estado: 'SP',
  especialidade: 'Optometria Clínica',
};

export const mockPacientes: Paciente[] = [
  {
    id: '1',
    nome: 'Maria Silva Santos',
    cpf: '123.456.789-00',
    dataNascimento: '1985-04-12',
    telefone: '(11) 98765-4321',
    email: 'maria.silva@email.com',
    ultimaConsulta: '2025-03-10',
    status: 'ativo',
    sexo: 'F',
  },
  {
    id: '2',
    nome: 'João Carlos Oliveira',
    cpf: '987.654.321-00',
    dataNascimento: '1972-08-25',
    telefone: '(11) 91234-5678',
    email: 'joao.oliveira@email.com',
    ultimaConsulta: '2024-03-05',
    status: 'retorno',
    sexo: 'M',
  },
  {
    id: '3',
    nome: 'Ana Carolina Pereira',
    cpf: '456.789.123-00',
    dataNascimento: '1998-11-03',
    telefone: '(11) 93456-7890',
    email: 'ana.pereira@email.com',
    ultimaConsulta: '2025-02-20',
    status: 'ativo',
    sexo: 'F',
  },
  {
    id: '4',
    nome: 'Roberto Ferreira Lima',
    cpf: '321.654.987-00',
    dataNascimento: '1960-06-18',
    telefone: '(11) 92345-6789',
    email: 'roberto.lima@email.com',
    ultimaConsulta: '2024-02-14',
    status: 'inativo',
    sexo: 'M',
  },
  {
    id: '5',
    nome: 'Isabela Mendes Costa',
    cpf: '654.321.098-00',
    dataNascimento: '2005-01-30',
    telefone: '(11) 94567-8901',
    email: 'isabela.costa@email.com',
    ultimaConsulta: '2025-01-15',
    status: 'ativo',
    sexo: 'F',
  },
  {
    id: '6',
    nome: 'Carlos Eduardo Souza',
    cpf: '789.012.345-00',
    dataNascimento: '1990-09-07',
    telefone: '(11) 95678-9012',
    email: 'carlos.souza@email.com',
    ultimaConsulta: '2024-01-20',
    status: 'retorno',
    sexo: 'M',
  },
];

export const mockProntuarios: Prontuario[] = [
  {
    id: 'p1',
    pacienteId: '1',
    data: '2025-03-10',
    odEsferico: -2.25,
    odCilindrico: -0.75,
    odEixo: 180,
    oeEsferico: -2.0,
    oeCilindrico: -0.5,
    oeEixo: 175,
    dnpOD: 32,
    dnpOE: 31,
    acuidadeOD: '20/20',
    acuidadeOE: '20/20',
    pressaoOD: 14,
    pressaoOE: 13,
    observacoes: 'Paciente com miopia estável. Recomendado uso integral dos óculos.',
    anamnese: {
      usaOculos: true,
      tempoUso: '5 anos',
      historicoFamiliar: true,
      diabetes: false,
      hipertensao: false,
      queixaPrincipal: 'Dificuldade de enxergar longe',
    },
  },
  {
    id: 'p2',
    pacienteId: '1',
    data: '2024-02-15',
    odEsferico: -2.0,
    odCilindrico: -0.75,
    odEixo: 178,
    oeEsferico: -1.75,
    oeCilindrico: -0.5,
    oeEixo: 172,
    dnpOD: 32,
    dnpOE: 31,
    acuidadeOD: '20/25',
    acuidadeOE: '20/25',
    observacoes: 'Leve progressão da miopia.',
  },
  {
    id: 'p3',
    pacienteId: '2',
    data: '2024-03-05',
    odEsferico: 1.5,
    odAdicao: 2.0,
    oeEsferico: 1.75,
    oeAdicao: 2.0,
    dnpOD: 33,
    dnpOE: 32,
    acuidadeOD: '20/30',
    acuidadeOE: '20/30',
    pressaoOD: 16,
    pressaoOE: 15,
    observacoes: 'Presbiopla moderada. Indicado lente progressiva.',
    anamnese: {
      usaOculos: true,
      tempoUso: '10 anos',
      historicoFamiliar: false,
      diabetes: true,
      hipertensao: true,
      medicamentos: 'Metformina, Losartana',
      queixaPrincipal: 'Dificuldade para ler de perto',
    },
  },
];

export const mockAgendamentos: Agendamento[] = [
  {
    id: 'a1',
    pacienteId: '3',
    pacienteNome: 'Ana Carolina Pereira',
    data: '2026-03-11',
    hora: '09:00',
    tipo: 'consulta',
    status: 'confirmado',
  },
  {
    id: 'a2',
    pacienteId: '5',
    pacienteNome: 'Isabela Mendes Costa',
    data: '2026-03-11',
    hora: '10:00',
    tipo: 'retorno',
    status: 'agendado',
  },
  {
    id: 'a3',
    pacienteId: '1',
    pacienteNome: 'Maria Silva Santos',
    data: '2026-03-11',
    hora: '14:00',
    tipo: 'consulta',
    status: 'agendado',
  },
  {
    id: 'a4',
    pacienteId: '2',
    pacienteNome: 'João Carlos Oliveira',
    data: '2026-03-12',
    hora: '09:30',
    tipo: 'retorno',
    status: 'agendado',
  },
  {
    id: 'a5',
    pacienteId: '6',
    pacienteNome: 'Carlos Eduardo Souza',
    data: '2026-03-12',
    hora: '11:00',
    tipo: 'consulta',
    status: 'agendado',
  },
  {
    id: 'a6',
    pacienteId: '4',
    pacienteNome: 'Roberto Ferreira Lima',
    data: '2026-03-13',
    hora: '15:00',
    tipo: 'consulta',
    status: 'agendado',
  },
];
